### ISSUE TITLE
kali linux ?

### ISSUE THREAD

**Issue by MohamedWn** [Miiden/EyeSpy#1]
how to run in kali linux

**Comment by Miiden** [comment]
Hi @MohamedWn,

The project is designed to run specifically on a windows environment for Penetration Testing Engagements in Enterprise Environments. it was created with that goal in mind specifically.

With that said, Kali should have `pwsh` installed, and you may be able to run the tool through that, though it has not been tested in that environment nor is there any current intention to test its capabilities fully within that.

Cheers,
Miiden
